name: docker

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REGISTRY: hub.docker.com

on:
  push:
    branches: [ main, master, prod ]
    tags: [ v* ]
  repository_dispatch:
    types: [docker]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  application:
    env:
      IMAGE:  ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - 
      id: meta
      name: docker metadata
      uses: docker/metadata-action@v5
      with:
        flavor: latest=true
        images: ${{ env.IMAGE }}
        tags: |
          type=schedule
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    -
      name: setup qemu
      uses: docker/setup-qemu-action@v3
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: authenticate
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    -
      id: push
      name: build and push
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
